---
title: 'Elke Windschitl'
page-layout: full
---

```{=html}
<style>
  .name {
  letter-spacing: 20px;
  color: $gray;
  text-align: center;
  font-weight: 1000;
  font-size: 40px;
  }
  
  .section-head {
  color: $gray;
  letter-spacing: 10px;
  text-align: left;
  font-weight: 1000;
  font-size: 26px;
  }
  
  .text-style-1 {
  color: $gray;
  text-align: center;
  font-size: 20px;
  }
  
  .text-style-2 {
  color: $gray;
  text-align: left;
  font-size: 20px;
  }
  
.menu {
  list-style: none;
  padding: 0;
  margin: 0;
}

.menu li {
  display: inline-block;
  margin-right: 30px;
}

.menu li a {
  text-decoration: none;
  color: #333;
  font-size: 12px; /* Adjust the font size */
}


</style>
```
<!-- <p class="name"> -->

<!-- Elke Windschitl -->

<!-- </p> -->

<!-- <p class="text-style-1"> -->

<!-- elke.windschitl\@gmail.com \| [elkewind.github.io](https://elkewind.github.io/) \| [GitHub](https://github.com/elkewind) \| [LinkedIn](https://www.linkedin.com/in/elke-windschitl-37a330149/) \| Santa Barbara, CA -->

<!-- </p> -->

[Download Resume](images/Windschitl_Elke_Resume.pdf)

<ul class="menu">

<li><a href="#summary">Summary of Qualifications</a></li>

<li><a href="#edu">Education</a></li>

<li><a href="#projs">Data Science Projects</a></li>

<li><a href="#fellow">Professional Research Experience</a></li>

<li><a href="#add">Additional Employment</a></li>

<li><a href="#skills">Skills & Certifications</a></li>

</ul>

------------------------------------------------------------------------

<p class="section-head" id="summary">

**SUMMARY OF QUALIFICATIONS**

</p>

<p class="text-style-2">

-   3 years of scientific programming experience in R; 1 year of experience in Python; experience in SQL.
-   Experienced in data preparation, data visualization, descriptive statistics, and geospatial analysis in R.
-   Strong foundation in inferential statistics, machine learning, and environmental modeling.
-   Efficiently work within collaborative teams; equally at ease working independently; strong communication.
-   Passion for investigating and applying technical solutions to social and environmental challenges.

</p>

------------------------------------------------------------------------

<p class="section-head" id="edu">

**EDUCATION**

</p>

<p class="text-style-2">

<strong>Master of Environmental Data Science</strong>, 3.97 GPA (6/23)<br> <strong>Bren School of Environmental Science & Management --- University of California, Santa Barbara (UCSB)</strong>

<blockquote><u>Leadership:</u> Dean's Advisory Council Representative, Master's Curriculum Committee Representative<br> <u>Highlighted Coursework:</u> Geospatial Analysis and Remote Sensing, Modeling Environmental Systems, Statistics for Environmental Data Science, Machine Learning in Environmental Science, Data Visualization and Communication, Ethics and Bias in Environmental Data Science, Team Science, Intro to R Shiny</blockquote>

</p>

<p class="text-style-2">

<strong>Bachelor of Science in Biology with Honors</strong>, 4.00 GPA (5/20)<br> <strong>College of Agriculture and Life Sciences --- Iowa State University (ISU)</strong>

<blockquote><u>Involvement:</u> National Student Exchange Program (University of Hawai'i at Hilo, Fall 2018; California State University, Monterey Bay, Spring 2020), Cultural Ambassador (Fall 2020), Women in Science and Engineering Student Role Model (Spring 2018, Spring 2019, Fall 2020)<br> <u>Highlighted Coursework:</u> Introduction to Renewable Resources, Field Ecology in Montana, Environmental Ethics, Natural Resource Management under the North American Model of Conservation, Comparative Chordate Anatomy, Fundamentals of Public Speaking, Written Oral Visual and Electronic Composition</blockquote>

</p>

------------------------------------------------------------------------

<p class="section-head" id="projs">

**DATA SCIENCE PROJECTS**

</p>

<p class="text-style-2">

<strong>Master's Capstone Project: Developing a Data Pipeline for Kelp Forest Modeling</strong> (1/23--6/23)<br> <strong>Role:</strong> Project Manager \| <strong>Client:</strong> Ocean Rainforest & Natalie Dornan UCSB

<ul>

<li>Aligned spatiotemporal resolution of 13 spatial data sets in R with *terra*, *raster*, & *sf*, to create a synthesized dataset containing oceanographic factors and metrics of giant kelp distribution as a deliverable for clients.</li>

<li>Performed maximum entropy species distribution modeling in R with *ENMeval* to estimate where on the Santa Barbara coastline has the highest predicted habitat suitability for kelp cultivation and restoration.</li>

<li>Created visualizations in R with *gpplot2*, *leaflet*, & *tmap* to communicate the spatial distribution of kelp, temperature, depth, and nutrients in the Santa Barbara Channel as well as identify data gaps.</li>

<li>Managed project deadlines, deliverables, and communication with Zoom, Slack, Docs, and GitHub Projects.</li>

</ul>

<strong>Statistics Course Project: Identifying Key Traits in Hawaiian Fish that Predict Risk of Extinction </strong>(10/22--12/22)

<ul>

<li>Planned and executed a study using existing data to answer questions about fish extinction vulnerability.</li>

<li>Retrieved, filtered, and joined large data tables from FishBase and the International Union for Conservation of Nature (IUCN) Red List application programming interface (API) in R with *dplyr*, *rfishbase*, and *rredlist*..</li>

<li>Leveraged *stats* to run a series of logistic regression models to investigate the probability of a species being listed as threatened on the IUCN Red List based on characteristics such as endemism or length.</li>

<li>Communicated study results by creating *ggplot2* visualizations and writing an online Quarto report.</li>

</ul>

</p>

------------------------------------------------------------------------

<p class="section-head" id="fellow">

**PROFESSIONAL RESEARCH EXPERIENCE**

</p>

<p class="text-style-2">

<strong>Animal Behavior Research Batten Fellow</strong> (7/21--9/21)<br> <strong>Virginia Aquarium & Marine Science Center, Virginia Beach, VA</strong>

<ul>

<li>Integrated the use of ZooMonitor --- a digital animal behavior monitoring tool --- at the aquarium by developing workflows and creating training materials for teaching other staff to use Zoo Monitor.</li>

<li>Collaborated with animal care staff to develop research questions to better understand how target animals' behavior changed based on time of day, location, guest count, etc.</li>

<li>Collected and analyzed behavior data of 2 seals and 1 crow using ZooMonitor software and R.</li>

<li>Presented research results to \~50 aquarium staff via a 45-minute Zoom PowerPoint presentation to inform science-based animal care procedure changes at the aquarium.</li>

</ul>

<strong>Research Assistant</strong> (1/19--12/19, 7/20--8/20)<br> <strong>Iowa State University Janke Lab, Ames, IA</strong>

<ul>

<li>Processed, analyzed, and visualized extensive quail audio data using R, Raven Pro, Excel, and PowerPoint.</li>

<li>Developed 3 research questions and methods of investigation for assessing the use of autonomous recording units to study Northern bobwhite quail and support the National Bobwhite Conservation Initiative.</li>

<li>Presented a research poster at the National Conference on Undergraduate Research detailing how ARUs can be used by the Iowa DNR to monitor occupancy of quail in place of labor-intensive point count surveys.</li>

<li>Followed detailed instructions to assist with miscellaneous lab and field tasks to help other lab members such as drying and weighing prairie grass biomass samples, assisting with line transect surveys, etc.</li>

</ul>

<strong>Animal Behavior Research Intern</strong> (6/19--8/19)<br> <strong>Saint Louis Zoo, Saint Louis, MO</strong>

<ul>

<li>Collected bear and primate behavior data by conducting live observations apart an 8-person team to inform future animal care decisions at the zoo.</li>

<li>Collected viper behavior data by conducting independent video observations using Observer XT to contribute to a study investigating whether viper tongue flicks are an indicator of stress.</li>

<li>Collected mother-infant antelope behavior data by conducting independent video observations using Observer XT to contribute to a 30+ year study to help inform future care of mother-infant pairs.</li>

</ul>

</p>

------------------------------------------------------------------------

<p class="section-head" id="add">

**ADDITIONAL EXPERIENCE**

</p>

<p class="text-style-2">

<strong>Environmental Education Creative Collaborator</strong> (6/18--present)<br> <strong>The LENA Project</strong>, Iowa City, IA<br> Create digital content and marketing materials to communicate the organization's mission and projects via graphic design and illustration using Canva, Adobe Photoshop, and Procreate as contract and volunteer work; brainstorm project ideas; archive work and metadata from previous projects.

<strong>Cashier</strong> (1/22--7/22)<br> <strong>Whole Foods</strong>, Seattle, WA<br> Provided excellent customer service and communication while cashiering, bagging, and monitoring self-checkout machines; trained 8 new team members on standard operating procedures in the customer service department.

</p>

------------------------------------------------------------------------

<p class="section-head" id="skills">

**SKILLS & CERTIFICATIONS**

</p>

<p class="text-style-2">

<strong>Programming Languages:</strong> R (proficient); Python, SQL (competent); Bash (beginner)<br> <strong>Other Digital Literacy:</strong> GitHub, Git, Microsoft 365 (proficient); Google Earth Engine, ArcGIS (competent)<br> <strong>Certifications:</strong> Fundamentals of GIS, GIS Data Formats, Design, and Quality, University of California, Davis (3/21)

</p>

------------------------------------------------------------------------
